package com.example.lyc.springboot.demo.model;

public class YourModelName {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Test.id
     *
     * @mbggenerated Sun Dec 03 00:52:59 CST 2023
     */
    private String id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Test.id
     *
     * @return the value of Test.id
     *
     * @mbggenerated Sun Dec 03 00:52:59 CST 2023
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Test.id
     *
     * @param id the value for Test.id
     *
     * @mbggenerated Sun Dec 03 00:52:59 CST 2023
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }
}